services:
  kafka-ui-dev:
    container_name: kafka-ui-dev
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8088:8080"
    depends_on:
      kafka1-dev:
        condition: service_healthy
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml
  kafka1-dev:
    container_name: kafka1-dev
    image: "bitnami/kafka:3.5"
    ports:
      - 9192:9092 # internal broker listener
      - 9193:9093 # controller
      - 9194:9094 # external listener
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=EXTERNAL://10.0.0.34:9194,PLAINTEXT://kafka1-dev:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1-dev:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LOG_RETENTION_MS=604800000
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_NODE_ID=1
    volumes:
      - ./data/bitnami/kafka1:/bitnami/kafka
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics.sh",
          "--list",
          "--bootstrap-server",
          "localhost:9092",
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
